<?php

declare(strict_types=1);

namespace Sigma\OfflinePayment\Observer;

use Magento\Framework\Event\Observer;
use Magento\Framework\Event\ObserverInterface;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\DB\Transaction;
use Magento\Sales\Api\OrderRepositoryInterface;
use Magento\Sales\Model\Order;
use Magento\Sales\Model\Service\InvoiceService;
use Magento\Store\Model\ScopeInterface;
use Psr\Log\LoggerInterface;
use Sigma\OfflinePayment\Model\OfflinePayment;

class AutoInvoice implements ObserverInterface
{
    /**
     * @param InvoiceService $invoiceService
     * @param Transaction $transaction
     * @param ScopeConfigInterface $scopeConfig
     * @param OrderRepositoryInterface $orderRepository
     * @param LoggerInterface $logger
     */
    public function __construct(
        private readonly InvoiceService $invoiceService,
        private readonly Transaction $transaction,
        private readonly ScopeConfigInterface $scopeConfig,
        private readonly OrderRepositoryInterface $orderRepository,
        private readonly LoggerInterface $logger
    ) {
    }

    /**
     * Auto-generate invoice on order placement
     *
     * @param Observer $observer
     * @return void
     */
    public function execute(Observer $observer): void
    {
        /** @var Order $order */
        $order = $observer->getEvent()->getOrder();

        if (!$order || !$order->getId()) {
            return;
        }

        // Check if payment method is our offline method
        $paymentMethod = $order->getPayment()->getMethod();
        if ($paymentMethod !== OfflinePayment::CODE) {
            return;
        }

        // Check if auto-invoice is enabled in admin config
        $autoInvoice = $this->scopeConfig->isSetFlag(
            'payment/sigma_offline_payment/auto_invoice',
            ScopeInterface::SCOPE_STORE,
            $order->getStoreId()
        );

        if (!$autoInvoice) {
            return;
        }

        // Skip if order already has invoices or cannot be invoiced
        if (!$order->canInvoice()) {
            return;
        }

        try {
            $invoice = $this->invoiceService->prepareInvoice($order);
            $invoice->setRequestedCaptureCase(\Magento\Sales\Model\Order\Invoice::CAPTURE_ONLINE);
            $invoice->register();

            // Save invoice and order
            $transactionSave = $this->transaction
                ->addObject($invoice)
                ->addObject($order);
            $transactionSave->save();

            // Add comment to order
            $order->addCommentToStatusHistory(
                __('Invoice #%1 auto-generated by Offline Payment Method.', $invoice->getIncrementId())
            );
            $this->orderRepository->save($order);
        } catch (\Exception $e) {
            $this->logger->error(
                'Sigma_OfflinePayment: Auto-invoice generation failed for Order #'
                . $order->getIncrementId() . ': ' . $e->getMessage()
            );
        }
    }
}
